### ISSUE TITLE
file structure has critical error

### ISSUE THREAD

**Issue by sunwoo0706** [neulsom-EZY/EZY-client#19]
레포에 굉장히 큰 문제가 있네요..
아마도 `CRA`의 상위 디렉터리를 `IDE`로 열고 가끔씩 터미널에서 `change directory`를 까먹고 `npm` 명령어를 실행하여 생성된 문제인것 같습니다. 이러한 이중 디렉터리 형태로 원격저장소(github)등에 올리면 나중에 큰 문제가 발생할 수 있습니다. 지금 당장 바꾸세요. 그리고 상위 디렉터리에서 폴더나 파일은 다 삭제 하세요.

---

<img width="160" src="https://user-images.githubusercontent.com/60869316/123377413-04c29000-d5c7-11eb-9a92-5dbd13dcdb82.png">

 그리고 위 디렉터리를 `root` 디렉터리로 정하고 다시 올리시는게 좋을것 같습니다.

---

<img width="160" alt="2021-06-25_15-09-49" src="https://user-images.githubusercontent.com/60869316/123378219-697dea80-d5c7-11eb-9253-1c43de20f98f.png">

위와 같이 여러 `nodeJs`의 종속성 파일들이 담겨져있는 `node_modules`이 원격저장소에 올라가는것은 패키지의 의미를 퇴색시킵니다.

**Comment by sunwoo0706** [comment]
깃허브는 잘 정리되어있고 가공할 만한 코드 리뷰 기능을 가지고 있으니, 코드 리뷰 기능을 적극적으로 사용하시면 좋을것 같습니다.

**Comment by Nayejun** [comment]
말씀 감사합니다.

안 그래도 저희 또한 그 문제를 인지하여, 해결방안을 구상하던 중이었습니다.
말씀해주신 내용을 토대로 최대한 빠르게 수정하겠습니다.

**Comment by sunwoo0706** [comment]
#20 고치셨네요 !!
