### ISSUE TITLE
Logo.js 수정이 필요합니다.

### ISSUE THREAD

**Issue by Nayejun** [neulsom-EZY/EZY-client#29]
![Screen Shot 2021-07-05 at 4 59 02 PM](https://user-images.githubusercontent.com/67637706/124464163-cc912d80-ddce-11eb-88e9-e01bc6e5563f.png)

앞서 수정 요청드렸던 아이폰 UI 이미지들은 수정이 잘 진행된 듯 한데,
Logo.js 에서 SVG 핸들링을 다시 진행해야할 것 같습니다 😉
현재 로고의 width 부분이 심각하게 비효율적입니다 ㅠㅠ
화이팅 !!

**Comment by KimGiHong** [comment]
저도 로고 width, height 문제는 알고 있지만 최대한 margin을 이용하지 않고 맞추기 위해 일단 저렇게 해두었던 건데 계속 수정해보겠습니다.
