### ISSUE TITLE
901px ~ 1130px에서 생기는 오른쪽 여백

### ISSUE THREAD

**Issue by KimGiHong** [neulsom-EZY/EZY-client#34]
<img width="1128" alt="스크린샷 2021-07-13 오전 11 51 01" src="https://user-images.githubusercontent.com/68697807/125382802-52196c80-e3d1-11eb-9126-e1ba2cab6c20.png">

901px ~ 1130px 오른쪽 여백이 있습니다.

**Comment by Nayejun** [comment]
해결 완료 😎
